ALTER TABLE NOTIFICATIONS ADD NOTIFICATION_GROUP VARCHAR2(255);
COMMENT ON COLUMN NOTIFICATIONS.NOTIFICATION_GROUP IS 'Which LDAP group to send notification to.';

DELETE FROM NOTIFICATIONS;
ALTER TABLE NOTIFICATIONS DROP COLUMN UUN;