DELETE FROM USER_NOTIFICATION_AUDIT;

ALTER TABLE USER_NOTIFICATION_AUDIT DROP COLUMN UUN;
ALTER TABLE USER_NOTIFICATION_AUDIT DROP COLUMN AUDIT_DESCRIPTION;


ALTER TABLE USER_NOTIFICATION_AUDIT ADD ( NOTIFICATION_ID NVARCHAR2(32) );
COMMENT ON COLUMN USER_NOTIFICATION_AUDIT.NOTIFICATION_ID IS 'Notification to which the audit entry applies';

ALTER TABLE USER_NOTIFICATION_AUDIT ADD ( AUDIT_DESCRIPTION NCLOB );
COMMENT ON COLUMN USER_NOTIFICATION_AUDIT.AUDIT_DESCRIPTION IS 'Description of the audit entry';