

CREATE TABLE NOTIFICATIONS_ARCHIVE
 (
  NOTIFICATION_ID VARCHAR2(32) NOT NULL,
  PUBLISHER_ID VARCHAR2(256 BYTE) NOT NULL,
  TOPIC VARCHAR2(32) NOT NULL,
  PUBLISHER_NOTIFICATION_ID VARCHAR2(32),
  TITLE NVARCHAR2(255) NOT NULL,
  NOTIFICATION_BODY NCLOB NOT NULL,
  NOTIFICATION_URL VARCHAR2(256 BYTE),
  START_DATE DATE,
  END_DATE DATE,
  LAST_UPDATED DATE NOT NULL,
  NOTIFICATION_GROUP VARCHAR2(255),
  NOTIFICATION_GROUP_NAME VARCHAR2(255),
  ARCHIVE_DATE DATE DEFAULT SYSDATE NOT NULL,
 )
TABLESPACE notify_data;

ALTER TABLE NOTIFICATIONS_ARCHIVE ADD CONSTRAINT NOTIFICATIONS_ARCHIVE_PK PRIMARY KEY (NOTIFICATION_ID)
USING INDEX TABLESPACE NOTIFY_INDEX ENABLE;

COMMENT ON COLUMN NOTIFICATIONS_ARCHIVE.NOTIFICATION_ID IS 'The unique id of the notification';
COMMENT ON COLUMN NOTIFICATIONS_ARCHIVE.PUBLISHER_ID IS 'The unique id of the publisher';
COMMENT ON COLUMN NOTIFICATIONS_ARCHIVE.TOPIC IS 'Notification topic';
COMMENT ON COLUMN NOTIFICATIONS_ARCHIVE.PUBLISHER_NOTIFICATION_ID IS 'The unique id the publisher uses for the notification';
COMMENT ON COLUMN NOTIFICATIONS_ARCHIVE.TITLE IS 'Notification title';
COMMENT ON COLUMN NOTIFICATIONS_ARCHIVE.NOTIFICATION_BODY IS 'The body of the notification';
COMMENT ON COLUMN NOTIFICATIONS_ARCHIVE.NOTIFICATION_URL IS 'The url for the notification';
COMMENT ON COLUMN NOTIFICATIONS_ARCHIVE.START_DATE IS 'Start date for the notification';
COMMENT ON COLUMN NOTIFICATIONS_ARCHIVE.END_DATE IS 'End date for the notification';
COMMENT ON COLUMN NOTIFICATIONS_ARCHIVE.LAST_UPDATED IS 'Last updated date';
COMMENT ON COLUMN NOTIFICATIONS_ARCHIVE.NOTIFICATION_GROUP IS 'Which LDAP group to send notification to.';
COMMENT ON COLUMN NOTIFICATIONS_ARCHIVE.NOTIFICATION_GROUP_NAME IS 'Which LDAP group (name) to send notification to.';
COMMENT ON COLUMN NOTIFICATIONS_ARCHIVE.ARCHIVE_DATE IS 'Date record inserted into the archive table';


CREATE TABLE "NOTIFICATION_USERS_ARCHIVE"
   ("NOTIFICATION_ID" VARCHAR2(32) NOT NULL,
	"UUN" VARCHAR(64) NOT NULL,
	"LAST_UPDATED" DATE NOT NULL
   ) ;

ALTER TABLE NOTIFICATION_USERS_ARCHIVE ADD CONSTRAINT NOTIFICATION_USERS_ARCHIVE_PK PRIMARY KEY (NOTIFICATION_ID, UUN)
USING INDEX TABLESPACE NOTIFY_INDEX ENABLE;

COMMENT ON COLUMN NOTIFICATION_USERS_ARCHIVE.NOTIFICATION_ID IS 'Unique identifier for the notification (SYS GUID)';
COMMENT ON COLUMN NOTIFICATION_USERS_ARCHIVE.UUN IS 'UUN to which the notification applies';


CREATE TABLE "NOTIFICATION_ARCHIVE_ITEMS"
   ("NOTIFICATION_ID" VARCHAR2(32) NOT NULL
   ) ;

ALTER TABLE NOTIFICATION_ARCHIVE_ITEMS ADD CONSTRAINT NOTIFICATION_ARCHIVE_ITEMS_PK PRIMARY KEY (NOTIFICATION_ID)
USING INDEX TABLESPACE NOTIFY_INDEX ENABLE;
