INSERT INTO NOTIFICATION_UI_USERS (UUN, ORG_GROUP_DN) VALUES ('DenyAccess','ou=CSG,ou=UOE,ou=org,ou=grouper2,dc=authorise,dc=ed,dc=ac,dc=uk');

INSERT INTO NOTIFICATION_UI_USER_ROLES (UUN,ROLE_CODE) VALUES ('DenyAccess','DENYACCESS');
