CREATE INDEX NOTIFY.END_DATE_NIND ON NOTIFY.NOTIFICATIONS (END_DATE);

ALTER TABLE NOTIFICATION_USERS ADD LAST_UPDATED DATE DEFAULT SYSDATE;

CREATE INDEX NOTIFY.END_DATE_UIND ON NOTIFY.NOTIFICATION_USERS (LAST_UPDATED);

ALTER TABLE NOTIFICATIONS MODIFY PUBLISHER_NOTIFICATION_ID VARCHAR2(256 BYTE);

ALTER TABLE NOTIFICATIONS MODIFY NOTIFICATION_URL VARCHAR2(512 BYTE); 



