ALTER TABLE NOTIFICATIONS ADD NOTIFICATION_GROUP VARCHAR2(255);
COMMENT ON COLUMN NOTIFICATION_USERS.NOTIFICATION_GROUP IS 'Which LDAP group to send notification to.';

ALTER TABLE NOTIFICATIONS DROP COLUMN UUN;