DELETE FROM USER_NOTIFICATION_AUDIT;

ALTER TABLE USER_NOTIFICATION_AUDIT RENAME COLUMN UUN TO NOTIFICATION_ID;
ALTER TABLE USER_NOTIFICATION_AUDIT MODIFY (
	NOTIFICATION_ID NVARCHAR2(32),
	AUDIT_DESCRIPTION NCLOB
);
