CREATE TABLE OFFICE365_SUBSCRIPTION  
(SUBSCRIPTION_ID VARCHAR2(128),  
SUBSCRIPTION_RENEW DATE,  
SUBSCRIPTION_EXPIRY DATE,  
LAST_UPDATED DATE DEFAULT SYSDATE) 
TABLESPACE notify_data; 

ALTER TABLE OFFICE365_SUBSCRIPTION ADD CONSTRAINT OFFICE365_SUBSCRIPTION_PK PRIMARY KEY (SUBSCRIPTION_ID) 
USING INDEX 
TABLESPACE NOTIFY_INDEX  ENABLE; 

COMMENT ON COLUMN OFFICE365_SUBSCRIPTION.SUBSCRIPTION_ID IS 'The unique id of the subscription';
COMMENT ON COLUMN OFFICE365_SUBSCRIPTION.SUBSCRIPTION_RENEW IS 'The date time when this subscription is renewed';
COMMENT ON COLUMN OFFICE365_SUBSCRIPTION.SUBSCRIPTION_EXPIRY IS 'The date time when this subscription will expire';
COMMENT ON COLUMN OFFICE365_SUBSCRIPTION.LAST_UPDATED IS 'Last updated date';
COMMENT ON TABLE OFFICE365_SUBSCRIPTION  IS 'The table stores office 365 subscription details';

CREATE OR REPLACE PUBLIC SYNONYM OFFICE365_SUBSCRIPTION FOR NOTIFY.OFFICE365_SUBSCRIPTION;

GRANT select,insert,update,delete on OFFICE365_SUBSCRIPTION TO notify_user;


