CREATE TABLE NOTIFICATION_USERS (
	NOTIFICATION_ID VARCHAR2(32),
	UUN VARCHAR2(64)
) TABLESPACE NOTIFY_DATA;

ALTER TABLE NOTIFICATION_USERS ADD CONSTRAINT NOTIFICATION_USERS_PK PRIMARY KEY (NOTIFICATION_ID) 
USING INDEX 
TABLESPACE NOTIFY_INDEX ENABLE; 

COMMENT ON COLUMN NOTIFICATION_USERS.NOTIFICATION_ID IS 'Unique identifier for the notification (SYS GUID)';
COMMENT ON COLUMN NOTIFICATION_USERS.UUN IS 'UUN to which the notification applies';

CREATE OR REPLACE PUBLIC SYNONYM NOTIFICATION_USERS FOR NOTIFY.NOTIFICATION_USERS;

GRANT SELECT,INSERT,UPDATE,DELETE ON NOTIFICATION_USERS TO NOTIFY_USER;