CREATE TABLE PUBLISHER_DETAILS 
(PUBLISHER_ID VARCHAR2(10) NOT NULL,
PUBLISHER_DESCRIPTION NVARCHAR2(255),
PUBLISHER_KEY VARCHAR2(32),
PUBLISHER_TYPE VARCHAR2(4) NOT NULL,
STATUS VARCHAR2(1) NOT NULL,
LAST_UPDATED DATE DEFAULT SYSDATE NOT NULL )
TABLESPACE notify_data;

COMMENT ON COLUMN PUBLISHER_DETAILS.PUBLISHER_ID IS 'The unique id of publisher';
COMMENT ON COLUMN PUBLISHER_DETAILS.PUBLISHER_DESCRIPTION IS 'The description of the publisher';
COMMENT ON COLUMN PUBLISHER_DETAILS.PUBLISHER_KEY IS 'Unique key for the publisher, used to validate certain publisher activities';
COMMENT ON COLUMN PUBLISHER_DETAILS.PUBLISHER_TYPE IS 'Type of publisher';
COMMENT ON COLUMN PUBLISHER_DETAILS.STATUS IS 'Status of publisher, (A)ctive or (I)nactive';
COMMENT ON COLUMN PUBLISHER_DETAILS.LAST_UPDATED IS 'Last updated date';

ALTER TABLE PUBLISHER_DETAILS ADD CONSTRAINT PUBLISHER_DETAILS_PK PRIMARY KEY (PUBLISHER_ID)
USING INDEX 
TABLESPACE NOTIFY_INDEX  ENABLE;

CREATE TABLE SUBSCRIBER_DETAILS
(SUBSCRIBER_ID VARCHAR2(10),
SUBSCRIBER_DESCRIPTION NVARCHAR2(255),
SUBSCRIBER_TYPE VARCHAR2(4),
STATUS VARCHAR2(1),
LAST_UPDATED DATE DEFAULT SYSDATE NOT NULL)
TABLESPACE notify_data;

ALTER TABLE SUBSCRIBER_DETAILS ADD CONSTRAINT SUBSCRIBER_DETAILS_PK PRIMARY KEY (SUBSCRIBER_ID)
USING INDEX 
TABLESPACE NOTIFY_INDEX  ENABLE;

COMMENT ON COLUMN SUBSCRIBER_DETAILS.SUBSCRIBER_ID IS 'The unique id of the subscriber';
COMMENT ON COLUMN SUBSCRIBER_DETAILS.SUBSCRIBER_DESCRIPTION IS 'The description of the subscriber';
COMMENT ON COLUMN SUBSCRIBER_DETAILS.SUBSCRIBER_TYPE IS 'Type of subscriber';
COMMENT ON COLUMN SUBSCRIBER_DETAILS.STATUS IS 'Status of subscriber, (A)ctive or (I)nactive';
COMMENT ON COLUMN SUBSCRIBER_DETAILS.LAST_UPDATED IS 'Last updated date';

CREATE TABLE TOPIC_SUBSCRIPTIONS
(SUBSCRIPTION_ID VARCHAR2(32) NOT NULL,
TOPIC VARCHAR2(32) NOT NULL,
SUBSCRIBER_ID VARCHAR2(32) NOT NULL,
STATUS VARCHAR2(1) NOT NULL,
LAST_UPDATED DATE DEFAULT SYSDATE NOT NULL)
TABLESPACE notify_data;

ALTER TABLE TOPIC_SUBSCRIPTIONS ADD CONSTRAINT TOPIC_SUBSCRIPTIONS_PK PRIMARY KEY (SUBSCRIPTION_ID)
USING INDEX 
TABLESPACE NOTIFY_INDEX  ENABLE;

COMMENT ON COLUMN TOPIC_SUBSCRIPTIONS.SUBSCRIPTION_ID IS 'The unique id of the subscription';
COMMENT ON COLUMN TOPIC_SUBSCRIPTIONS.TOPIC IS 'Topic subscribed to';
COMMENT ON COLUMN TOPIC_SUBSCRIPTIONS.SUBSCRIBER_ID IS 'ID of the subscriber';
COMMENT ON COLUMN TOPIC_SUBSCRIPTIONS.STATUS IS 'Status of subscription, (A)ctive or (I)nactive';
COMMENT ON COLUMN TOPIC_SUBSCRIPTIONS.LAST_UPDATED IS 'Last updated date';

CREATE TABLE NOTIFICATIONS
(NOTIFICATION_ID VARCHAR2(32) NOT NULL,
PUBLISHER_ID VARCHAR2(10) NOT NULL,
TOPIC VARCHAR2(32) NOT NULL,
PUBLISHER_NOTIFICATION_ID VARCHAR2(32),
TITLE NVARCHAR2(255) NOT NULL,
NOTIFICATION_BODY NCLOB NOT NULL,
NOTIFICATION_URL VARCHAR2(255),
START_DATE DATE,
END_DATE DATE,
UUN VARCHAR2(64),
LAST_UPDATED DATE DEFAULT SYSDATE NOT NULL)
TABLESPACE notify_data;

ALTER TABLE NOTIFICATIONS ADD CONSTRAINT NOTIFICATIONS_PK PRIMARY KEY (NOTIFICATION_ID)
USING INDEX 
TABLESPACE NOTIFY_INDEX  ENABLE;

COMMENT ON COLUMN NOTIFICATIONS.NOTIFICATION_ID IS 'The unique id of the notification';
COMMENT ON COLUMN NOTIFICATIONS.PUBLISHER_ID IS 'The unique id of the publisher';
COMMENT ON COLUMN NOTIFICATIONS.TOPIC IS 'Notification topic';
COMMENT ON COLUMN NOTIFICATIONS.PUBLISHER_NOTIFICATION_ID IS 'The unique id the publisher uses for the notification';
COMMENT ON COLUMN NOTIFICATIONS.TITLE IS 'Notification title';
COMMENT ON COLUMN NOTIFICATIONS.NOTIFICATION_BODY IS 'The body of the notification';
COMMENT ON COLUMN NOTIFICATIONS.NOTIFICATION_URL IS 'The url for the notification';
COMMENT ON COLUMN NOTIFICATIONS.START_DATE IS 'Start date for the notification';
COMMENT ON COLUMN NOTIFICATIONS.END_DATE IS 'End date for the notification';
COMMENT ON COLUMN NOTIFICATIONS.UUN IS 'UUN to which the notification applies';
COMMENT ON COLUMN NOTIFICATIONS.LAST_UPDATED IS 'Last updated date';

CREATE TABLE NOTIFICATION_PUSH_STATUS
(NOTIFICATION_ID VARCHAR2(32) NOT NULL,
SUBSCRIBER_ID VARCHAR2(32) NOT NULL,
PUSH_STATUS VARCHAR2(1) NOT NULL,
LAST_UPDATED DATE DEFAULT SYSDATE NOT NULL)
TABLESPACE notify_data;

ALTER TABLE NOTIFICATION_PUSH_STATUS ADD CONSTRAINT NOTIFICATION_PUSH_STATUS_PK PRIMARY KEY (NOTIFICATION_ID,SUBSCRIBER_ID)
USING INDEX 
TABLESPACE NOTIFY_INDEX  ENABLE;

COMMENT ON COLUMN NOTIFICATION_PUSH_STATUS.NOTIFICATION_ID IS 'Unique identifier for the notification';
COMMENT ON COLUMN NOTIFICATION_PUSH_STATUS.SUBSCRIBER_ID IS 'Unique identifier for the subscriber';
COMMENT ON COLUMN NOTIFICATION_PUSH_STATUS.PUSH_STATUS IS '(P)ending or (S)ent';
COMMENT ON COLUMN NOTIFICATION_PUSH_STATUS.LAST_UPDATED IS 'Last updated date';

CREATE TABLE NOTIFICATION_ERRORS
(ERROR_ID VARCHAR2(32) NOT NULL,
ERROR_CODE VARCHAR2(32) NOT NULL,
ERROR_DESCRIPTION NVARCHAR2(255) NOT NULL,
ERROR_DATE DATE DEFAULT SYSDATE NOT NULL)
TABLESPACE notify_data;

COMMENT ON COLUMN NOTIFICATION_ERRORS.ERROR_ID IS 'Unique identifier for the error';
COMMENT ON COLUMN NOTIFICATION_ERRORS.ERROR_CODE IS 'Error code';
COMMENT ON COLUMN NOTIFICATION_ERRORS.ERROR_DESCRIPTION IS 'Error description';
COMMENT ON COLUMN NOTIFICATION_ERRORS.ERROR_DATE IS 'Date of error';

ALTER TABLE NOTIFICATION_ERRORS ADD CONSTRAINT NOTIFICATION_ERRORS_PK PRIMARY KEY (ERROR_ID)
USING INDEX 
TABLESPACE NOTIFY_INDEX  ENABLE;

CREATE TABLE USER_NOTIFICATION_AUDIT
(AUDIT_ID VARCHAR2(32) NOT NULL,
UUN VARCHAR2(32),
PUBLISHER_ID VARCHAR2(10) NOT NULL,
ACTION VARCHAR2(32) NOT NULL,
AUDIT_DATE DATE DEFAULT SYSDATE NOT NULL)
TABLESPACE notify_data;

ALTER TABLE USER_NOTIFICATION_AUDIT ADD CONSTRAINT USER_NOTIFICATION_AUDIT_PK PRIMARY KEY (AUDIT_ID)
USING INDEX 
TABLESPACE NOTIFY_INDEX  ENABLE;

COMMENT ON COLUMN USER_NOTIFICATION_AUDIT.AUDIT_ID IS 'Unique identifier for audit entry';
COMMENT ON COLUMN USER_NOTIFICATION_AUDIT.UUN IS 'UUN to which the audit entry applies';
COMMENT ON COLUMN USER_NOTIFICATION_AUDIT.PUBLISHER_ID IS 'Unique identifier for the publisher';
COMMENT ON COLUMN USER_NOTIFICATION_AUDIT.ACTION IS 'Unique identifier for audit entry';
COMMENT ON COLUMN USER_NOTIFICATION_AUDIT.AUDIT_DATE IS 'Date for audit entry';


CREATE TABLE NOTIFICATION_UI_USERS
(UUN VARCHAR2(64) NOT NULL)
TABLESPACE notify_data;

ALTER TABLE NOTIFICATION_UI_USERS ADD CONSTRAINT NOTIFICATION_UI_USERS_PK PRIMARY KEY (UUN)
USING INDEX 
TABLESPACE NOTIFY_INDEX  ENABLE;

COMMENT ON COLUMN NOTIFICATION_UI_USERS.UUN IS 'uun with access to the ui';

CREATE TABLE NOTIFICATION_UI_USER_ROLES
(UUN VARCHAR2(64) NOT NULL,
ROLE_CODE VARCHAR2(10) NOT NULL)
TABLESPACE notify_data;

ALTER TABLE NOTIFICATION_UI_USER_ROLES ADD CONSTRAINT NOTIFICATION_UI_USER_ROLES_PK PRIMARY KEY (UUN,ROLE_CODE)
USING INDEX 
TABLESPACE NOTIFY_INDEX  ENABLE;

COMMENT ON COLUMN NOTIFICATION_UI_USER_ROLES.UUN IS 'uun assigned the role';
COMMENT ON COLUMN NOTIFICATION_UI_USER_ROLES.ROLE_CODE IS 'role assigned to the uun';

CREATE TABLE NOTIFICATION_UI_ROLES
(ROLE_CODE VARCHAR2(10),
ROLE_DESCRIPTION NVARCHAR2(255))
TABLESPACE notify_data;

ALTER TABLE NOTIFICATION_UI_ROLES ADD CONSTRAINT NOTIFICATION_UI_ROLES_PK PRIMARY KEY (ROLE_CODE)
USING INDEX 
TABLESPACE NOTIFY_INDEX  ENABLE;

COMMENT ON COLUMN NOTIFICATION_UI_ROLES.ROLE_CODE IS 'code for the role';
COMMENT ON COLUMN NOTIFICATION_UI_ROLES.ROLE_DESCRIPTION IS 'description of the role';




CREATE TABLE OFFICE365_SUBSCRIPTION  
(SUBSCRIPTION_ID VARCHAR2(128),  
SUBSCRIPTION_RENEW DATE,  
SUBSCRIPTION_EXPIRY DATE,  
LAST_UPDATED DATE DEFAULT SYSDATE) 
TABLESPACE notify_data; 


ALTER TABLE OFFICE365_SUBSCRIPTION ADD CONSTRAINT OFFICE365_SUBSCRIPTION_PK PRIMARY KEY (SUBSCRIPTION_ID) 
USING INDEX 
TABLESPACE NOTIFY_INDEX  ENABLE; 


COMMENT ON COLUMN OFFICE365_SUBSCRIPTION.SUBSCRIPTION_ID IS 'The unique id of the subscription';
COMMENT ON COLUMN OFFICE365_SUBSCRIPTION.SUBSCRIPTION_RENEW IS 'The date time when this subscription is renewed';
COMMENT ON COLUMN OFFICE365_SUBSCRIPTION.SUBSCRIPTION_EXPIRY IS 'The date time when this subscription will expire';
COMMENT ON COLUMN OFFICE365_SUBSCRIPTION.LAST_UPDATED IS 'Last updated date';
COMMENT ON TABLE OFFICE365_SUBSCRIPTION  IS 'The table stores office 365 subscription details';









